// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateUserCounter(ctx context.Context, arg UpdateUserCounterParams) error
}

var _ Querier = (*Queries)(nil)
