// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"m1thrandir225/lab-2-3-4/dto"
)

type Querier interface {
	CleanupExpiredCounters(ctx context.Context) error
	CreateHotpCounter(ctx context.Context, arg CreateHotpCounterParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetCurrentCounter(ctx context.Context, userID int64) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserRole(ctx context.Context, id int64) (dto.Role, error)
	IncreaseCounter(ctx context.Context, userID int64) (int64, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
