CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    otp_secret TEXT NOT NULL,
    is_2fa_enabled BOOLEAN NOT NULL DEFAULT FALSE
);

